# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/audio-journal',
                'doc_host': 'https://smith-kyle.github.io',
                'git_url': 'https://github.com/smith-kyle/audio-journal',
                'lib_path': 'audio_journal'},
  'syms': {'audio_journal.main': {'audio_journal.main.start': ('main.html#start', 'audio_journal/main.py')}, 'audio_journal.old_main': {}}}
