# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_temp.ipynb.

# %% auto 0
__all__ = ['say_something']

# %% ../nbs/00_temp.ipynb 3
def say_something(thing: str) -> None:
    "Say something that's passed in"
    return f'Hello {thing}'
