# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['start']

# %% ../nbs/00_main.ipynb 3
from .old_main import *
import multiprocessing

# %% ../nbs/00_main.ipynb 4
def start() -> None:
    try:
        record_process = multiprocessing.Process(target=recording_process)
        transcribe_process = multiprocessing.Process(target=transcribing_process)

        record_process.start()
        transcribe_process.start()

        record_process.join()
        transcribe_process.join()
    # Catch any kind of error and play error sound
    except Exception as e:
        play_error_sound()
        print(e)
