# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sounds.ipynb.

# %% auto 0
__all__ = ['get_current_dir', 'play_success_sound', 'play_error_sound', 'play_start_sound', 'play_stop_sound']

# %% ../nbs/02_sounds.ipynb 1
import os
from pydub import AudioSegment
from pydub.playback import play

# %% ../nbs/02_sounds.ipynb 2
def get_current_dir():
    return os.path.dirname(os.path.abspath(__file__))

def play_success_sound():
    success_song = AudioSegment.from_wav(os.path.join(get_current_dir(), "beeps/success.wav"))
    play(success_song)

def play_error_sound():
    error_song = AudioSegment.from_wav(os.path.join(get_current_dir(), "beeps/error.wav"))
    play(error_song)

def play_start_sound():
    start_song = AudioSegment.from_wav(os.path.join(get_current_dir(), "beeps/start.wav"))
    play(start_song)

def play_stop_sound():
    stop_song = AudioSegment.from_wav(os.path.join(get_current_dir(), "beeps/stop.wav"))
    play(stop_song)
